version: '2'
services:
    emisauthapp6-app:
        image: emisauthapp6
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://emisauthapp6-mariadb:3306/emisauthapp6
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    emisauthapp6-mariadb:
        extends:
            file: mariadb.yml
            service: emisauthapp6-mariadb
